title: SPAstef's Blog
description: A blog about stuff that I like
author: "Stefano Trevisani"

theme: minima

#math_engine: mathjax

base_url: /spastef.github.io
repository: spastef/spastef.github.io

# Minima social links
github_username: spastef
linkedin_username: stefano-trevisani

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

markdown: kramdown


#markdown: kramdown
#kramdown:
#    math_engine: katex

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - examples
    - temp
  